#!/bin/bash

# Web Help Desk
# Copyright (c) SolarWinds Worldwide, LLC
#
# Web Help Desk control script
#

# resolve links - $0 may be a softlink
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '.*/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done
 
# get the full path to the WebHelpDesk home 
if echo $PRG|grep "^/" >/dev/null 2>&1
then
FULLPATH=$PRG
else
  THIS_CMD=$PRG
  if echo $THIS_CMD|grep "^\./" >/dev/null 2>&1
  then 
     THIS_CMD=`basename $PRG`
  fi
  FULLPATH="`pwd`/$THIS_CMD"
fi
export EMBEDDED=${EMBEDDED:-true}
WHD_HOME=`dirname "$FULLPATH"`
$WHD_HOME/bin/whd "$@"
